#!/bin/bash
name=$(jq -r '.name' data.json | sed 's/.*/\u&/'); type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/'); height=$(jq -r '.height' data.json); weight=$(jq -r '.weight' data.json); awk -v n="$name" -v t="$type" -v h="$height" -v w="$weight" 'BEGIN {printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", n, t, w/10, h/10}'

