#!/bin/bash
name=$(jq -r '.name' data.json | sed 's/.*/\u&/') && height=$(jq -r '.height' data.json) && weight=$(jq -r '.weight' data.json) && type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/') && awk -v n="$name" -v h="$height" -v w="$weight" -v t="$type" 'BEGIN {printf "%s is of type %s, weighs %.1fkg, and is %.1fm tall.\n", n, t, w/10, h/10}'

